//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorID { get; set; }
        public string DonationCurrency { get; set; }
        public string DonationAmount { get; set; }
        public string DonorFName { get; set; }
        public string DonorLName { get; set; }
        public Nullable<decimal> DonorAccNo { get; set; }
        public Nullable<decimal> DonorTotal { get; set; }
        public string DonorCellphone { get; set; }
    }
}
