//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string PatientFName { get; set; }
        public string PatientSName { get; set; }
        public string PatientCellphone { get; set; }
        public string PatientEmail { get; set; }
        public string Medicating { get; set; }
        public string Race { get; set; }
        public int AreaID { get; set; }
        public string PatientAddress { get; set; }
    
        public virtual AreaAffected AreaAffected { get; set; }
    }
}
